[project]
name = "eda-explorer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "missingno>=0.5.2",
    "pandas>=2.3.1",
]
